reapply custom miraheze changes
miraheze/mediawiki pull request #1446
Opened 2021-04-08 22:08 UTC by RhinosF1

2021-04-11 21:40 UTC, Southparkfan requested changes

2021-04-11 21:40 UTC, Southparkfan commented on includes/deferred/CdnCacheUpdate.php
> +				$baseReq = [
indent

2021-04-11 21:40 UTC, Southparkfan commented on includes/deferred/CdnCacheUpdate.php
> +			// Southparkfan hack start (adds x-device)
Can we include documentation: **why** do we include an X-Device header on each purge?

2021-04-12 06:34 UTC, RhinosF1 commented on includes/deferred/CdnCacheUpdate.php
> +			// Southparkfan hack start (adds x-device)
We can but they are your hacks. Can you recall why?

2021-04-12 21:10 UTC, Southparkfan commented on includes/deferred/CdnCacheUpdate.php
> +			// Southparkfan hack start (adds x-device)
> In Varnish, we store two variants of an article: the mobile layout (via MobileFrontend) and the desktop version. This is done by running vcl_hash over the X-Device header. The X-Device header is set at Varnish level and can be one of ['mobile-tablet', 'desktop']. However, when purging a resource using merely the URL path, it's not possible to purge both the mobile and desktop variants. In order to purge properly, MediaWiki must set each possible X-Device value in the X-Device header, one per PURGE request.

2021-05-18 11:09 UTC, Reception123 commented
@RhinosF1 Since it's your task, do you want to add the comment left by SPF to the file?

2021-05-18 14:30 UTC, RhinosF1 commented
Did it mobile @Reception123 but there you go! Feel free to tidy up.

2021-05-22 14:23 UTC, Southparkfan approved these changes

2021-05-22 18:19 UTC, merged