Labeler: run only when the actor is dependabot
miraheze/mediawiki pull request #5023
Opened 2022-01-19 06:27 UTC by lens0021

- [ ] Test on https://github.com/lens0021/mediawiki

2022-01-19 06:35 UTC, Universal-Omega commented
Thanks so much for this! I've been meaning to get to this for more than a month now, but never really did.

2022-01-30 23:14 UTC, Universal-Omega requested changes

2022-01-30 23:14 UTC, Universal-Omega commented on .github/workflows/label.yml
> +    - if: github.actor == 'dependabot'
I think this just needs to be `${{ github.actor == 'dependabot[bot]' }}` (the `${{ }}` is just a personal preference, the [bot] should be necessary.)

2022-02-21 12:25 UTC, RhinosF1 commented
@lens0021: Can you please update the PR

2022-02-21 13:38 UTC, lens0021 commented
OK, though this PR itself is not passed, it is caused by `on: [pull_request_target]`. The next manual PR which is created after the REL1_37 branch is modified has been marked as skipped:

- https://github.com/lens0021/mediawiki/pull/1

And next PR by Dependabot has been labeled:

- https://github.com/lens0021/mediawiki/pull/2

2022-02-21 13:57 UTC, merged